### ISSUE TITLE
[BUG] AttributeError: 'RetrievalModelV2' object has no attribute 'to_top_k_encoder'

### ISSUE THREAD

**Issue by vs385** [NVIDIA-Merlin/models#893]
### Bug description
Getting error message
AttributeError: 'RetrievalModelV2' object has no attribute 'to_top_k_encoder'

### Steps/Code to reproduce bug

1. I'm running a notebook to train a retrieval model inside a container that's using as base image the merlin-tensorflow:22.10 image
2. I fitted a mm.RetrievalModelV2() model object trying to run it for prediction 
3. I keep getting the above AttributeError even though when checking the class code at merlin.models.tf.models.base
4. I checked the version of merlin-models running in my kernel (v 0.9.0) which is the latest version

### Expected behavior

Expected a topkmodel to be returned

### Environment details
- Merlin version: nvcr.io/nvidia/merlin/merlin-tensorflow:22.10
- Platform: ec2 g5 instance linux
- Python version: 3.8.10
- PyTorch version (GPU?):
- Tensorflow version (GPU?): tensorflow 2.9.1+nv22.8

**Comment by zhiruiwang** [comment]
`to_top_k_encoder` got introduced in https://github.com/NVIDIA-Merlin/models/pull/790, which is after the release of `merlin-models=0.9.0` in `merlin-tensorflow:22.10`. If you install from the main branch of `merlin-models` it should be fixed

**Comment by vs385** [comment]
Thanks
